### ISSUE TITLE
predict.sh error:path to child vcf file not found

### ISSUE THREAD

**Issue by soumyarao86** [ksablauskas/denovocnn#7]
Hello, 
I installed DeNovoConn following the instructions, but didn't find predict.sh.
So I copied it from here and executed the command but it failed.
The error shows the input file can't be found.
Can you please help? 
```
./predict.sh -w ~/research-data/wnt9b_mice_genome_seq/WGS_bam/denovoconn --child-vcf ../../Cox-2-9.hard-filtered.vcf -fv ~/research-data/wnt9b_mice_genome_seq/Cox_1529.vcf -mv ~/research-data/wnt9b_mice_genome_seq/Cox-4266.hard-filtered.vcf -cb ~/research-data/wnt9b_mice_genome_seq/WGS_bam/Cox-2-9.bam -fb ~/research-data/wnt9b_mice_genome_seq/WGS_bam/Cox_1529.bam -mb ~/research-data/wnt9b_mice_genome_seq/WGS_bam/Cox-4266-TA.bam -sm ~/research-data/wnt9b_mice_genome_seq/WGS_bam/dbsnp-150_chr.vcf -g ~/research-data/wnt9b_mice_genome_seq/WGS_bam/GRCm38.primary_assembly.genome.fa -m genome -o denovoconn_dragen_2-9  

Error: Path to child vcf file --child-vcf must be provided!
```

**Comment by gelana** [comment]
Hi @soumyarao86 , 

The up-to-dated version of DeNovoCNN is currently here: https://github.com/Genome-Bioinformatics-RadboudUMC/DeNovoCNN

**Comment by soumyarao86** [comment]
I can't install and run docker images in my WS.
Is there any way I can make it work on anaconda?

**Comment by soumyarao86** [comment]
I'm sorry but I think I am missing something here too.

```
$cd DeNovoCNN/
$ conda env create -f environment.yml

EnvironmentFileNotFound: '/home/srng3/DeNovoCNN/environment.yml' file not found
```

**Comment by gelana** [comment]
The first step is to clone (copy) the repository with the command:
`git clone https://github.com/Genome-Bioinformatics-RadboudUMC/DeNovoCNN.git`
Then you can execute the following and it should work:
`cd DeNovoCNN`
`conda env create -f environment.yml`

Please let me know if that worked

**Comment by soumyarao86** [comment]
Hi Gelana, I think installation worked well, thanks for guiding me through it.
But the manual prediction isn't working. I am trying to run it on mouse KOs.
I have passed dbsnp for snp model and the same file with indels for ins and del models.
I split the variants in 9 files but don't know how to input them all at once. part*txt or comma separated list of all parts isn't working.
So I ran with 1 part and got the following error and no output in the working dir.
```
(tensorflow_env) srng3@KC-DS-BioLinux:~/research-data/wnt9b_mice_genome_seq/WGS_bam/denovoconn$ ~/DeNovoCNN/DeNovoCNN/apply_denovocnn.sh -w=~/research-data/wnt9b_mice_genome_seq/WGS_bam/denovoconn/dnvcnn_dragen-2-9/ -v=part_variants00.txt -cb=../Cox-2-9.bam -fb=../Cox_1529.bam -mb=../Cox-4266-TA.bam -sm=../dbsnp-150_chr.vcf -im=../mgp.v5.indels.pass.chr.vcf -dm=-im=../mgp.v5.indels.pass.chr.vcf -g=../GRCm38.primary_assembly.genome.fa -o=prediction00.csv                 Start preprocessing step...
mkdir: cannot create directory ‘~/research-data/wnt9b_mice_genome_seq/WGS_bam/denovoconn/dnvcnn_dragen-2-9/’: No such file or directory
Preprocessing step finished.
Running DenovoCNN...
Start apply in parallel, n_jobs=-1

Start applying DeNovoCNN
Using 64 CPUs
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/srng3/anaconda3/envs/tensorflow_env/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/srng3/anaconda3/envs/tensorflow_env/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/srng3/DeNovoCNN/DeNovoCNN/denovonet/dataset.py", line 333, in apply_model_batch
    models_dict = load_models(models_cfg)
  File "/home/srng3/DeNovoCNN/DeNovoCNN/denovonet/dataset.py", line 294, in load_models
    'Substitution': tf.keras.models.load_model(models_cfg['snp_model'], compile=False),
  File "/home/srng3/anaconda3/envs/tensorflow_env/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 186, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/home/srng3/anaconda3/envs/tensorflow_env/lib/python3.8/site-packages/tensorflow/python/saved_model/loader_impl.py", line 110, in parse_saved_model
    raise IOError("SavedModel file does not exist at: %s/{%s|%s}" %
OSError: SavedModel file does not exist at: ../dbsnp-150_chr.vcf/{saved_model.pbtxt|saved_model.pb}
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/srng3/DeNovoCNN/DeNovoCNN/main.py", line 72, in <module>
    apply_models_on_trio(
  File "/home/srng3/DeNovoCNN/DeNovoCNN/denovonet/dataset.py", line 370, in apply_models_on_trio
    dataset.apply_model(
  File "/home/srng3/DeNovoCNN/DeNovoCNN/denovonet/dataset.py", line 135, in apply_model
    results = pool.map(
  File "/home/srng3/anaconda3/envs/tensorflow_env/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/srng3/anaconda3/envs/tensorflow_env/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
OSError: SavedModel file does not exist at: ../dbsnp-150_chr.vcf/{saved_model.pbtxt|saved_model.pb}
DenovoCNN finished.
Output in:
~/research-data/wnt9b_mice_genome_seq/WGS_bam/denovoconn/dnvcnn_dragen-2-9//prediction00.csv
```

**Comment by gelana** [comment]
Hi @soumyarao86 , 

Since you pass variant list to `-v` argument, there us no need to pass ` vcf `files anymore. 

parameters `-sm`, `-im`, `-dm` require paths to the models, so if DeNovoCNN is installed into `~/DeNovoCNN/DeNovoCNN` directory, then in your case the command will be:

`
~/DeNovoCNN/DeNovoCNN/apply_denovocnn.sh 
-w=~/research-data/wnt9b_mice_genome_seq/WGS_bam/denovoconn/dnvcnn_dragen-2-9/ 
-v=part_variants00.txt 
-cb=../Cox-2-9.bam 
-fb=../Cox_1529.bam 
-mb=../Cox-4266-TA.bam 
-sm=~/DeNovoCNN/DeNovoCNN/models/snp 
-im=~/DeNovoCNN/DeNovoCNN/models/ins 
-dm=~/DeNovoCNN/DeNovoCNN/models/del 
-g=../GRCm38.primary_assembly.genome.fa 
-o=prediction00.csv        
`

**Comment by soumyarao86** [comment]
Thanks . So do the models for SNP and Indels can be applied to mouse genome as well?
Can we provide dbSNP and indels for mouse?
 I am still getting this new error.
```
(base) srng3@KC-DS-BioLinux:~/research-data/wnt9b_mice_genome_seq/WGS_bam/denovoconn$ ~/DeNovoCNN/DeNovoCNN/apply_denovocnn.sh -w=~/research-data/wnt9b_mice_genome_seq/WGS_bam/denovoconn/dnvcnn_dragen-2-9/ -v=part_variants00.txt -cb=../Cox-2-9.bam -fb=../Cox_1529.bam -mb=../Cox-4266-TA.bam -sm=~/DeNovoCNN/DeNovoCNN/models/snp -im=~/DeNovoCNN/DeNovoCNN/models/ins -dm=~/DeNovoCNN/DeNovoCNN/models/del -g=../GRCm38.primary_assembly.genome.fa -o=prediction00.csv
Start preprocessing step...
mkdir: cannot create directory ‘~/research-data/wnt9b_mice_genome_seq/WGS_bam/denovoconn/dnvcnn_dragen-2-9/’: No such file or directory
Preprocessing step finished.
Running DenovoCNN...
Traceback (most recent call last):
  File "/home/srng3/DeNovoCNN/DeNovoCNN/main.py", line 24, in <module>
    from denovonet.dataset import apply_models_on_trio
  File "/home/srng3/DeNovoCNN/DeNovoCNN/denovonet/dataset.py", line 31, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
DenovoCNN finished.
Output in:
~/research-data/wnt9b_mice_genome_seq/WGS_bam/denovoconn/dnvcnn_dragen-2-9//prediction00.csv
```

**Comment by gelana** [comment]
I see that you a running under `base` environment. Before using DeNovoCNN you should activate the right environment running `conda activate tensorflow_env`.

We have never tested DeNovoCNN on mouse genome, in fact, we only used it on human data, so I'm curious how does it perform on mouse data. 

And I'm not sure, that I understood your question, but we haven't used dbSNP in our algorithm  :)

**Comment by soumyarao86** [comment]
Got it. But still errors persist!
(base) srng3@KC-DS-BioLinux:~/research-data/wnt9b_mice_genome_seq/WGS_bam/denovoconn$ conda activate tensorflow_env
(tensorflow_env) srng3@KC-DS-BioLinux:~/research-data/wnt9b_mice_genome_seq/WGS_bam/denovoconn$ ~/DeNovoCNN/DeNovoCNN/apply_denovocnn.sh -w=~/research-data/wnt9b_mice_genome_seq/WGS_bam/denovoconn/dnvcnn_dragen-2-9/ -v=part_variants00.txt -cb=../Cox-2-9.bam -fb=../Cox_1529.bam -mb=../Cox-4266-TA.bam -sm=~/DeNovoCNN/DeNovoCNN/models/snp -im=~/DeNovoCNN/DeNovoCNN/models/ins -dm=~/DeNovoCNN/DeNovoCNN/models/del -g=../GRCm38.primary_assembly.genome.fa -o=prediction00.csv
Start preprocessing step...
mkdir: cannot create directory ‘~/research-data/wnt9b_mice_genome_seq/WGS_bam/denovoconn/dnvcnn_dragen-2-9/’: No such file or directory
Preprocessing step finished.
Running DenovoCNN...
Start apply in parallel, n_jobs=-1

Start applying DeNovoCNN
Using 64 CPUs
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/srng3/anaconda3/envs/tensorflow_env/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/srng3/anaconda3/envs/tensorflow_env/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/srng3/DeNovoCNN/DeNovoCNN/denovonet/dataset.py", line 333, in apply_model_batch
    models_dict = load_models(models_cfg)
  File "/home/srng3/DeNovoCNN/DeNovoCNN/denovonet/dataset.py", line 294, in load_models
    'Substitution': tf.keras.models.load_model(models_cfg['snp_model'], compile=False),
  File "/home/srng3/anaconda3/envs/tensorflow_env/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 186, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/home/srng3/anaconda3/envs/tensorflow_env/lib/python3.8/site-packages/tensorflow/python/saved_model/loader_impl.py", line 110, in parse_saved_model
    raise IOError("SavedModel file does not exist at: %s/{%s|%s}" %
OSError: SavedModel file does not exist at: ~/DeNovoCNN/DeNovoCNN/models/snp/{saved_model.pbtxt|saved_model.pb}
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/srng3/DeNovoCNN/DeNovoCNN/main.py", line 72, in <module>
    apply_models_on_trio(
  File "/home/srng3/DeNovoCNN/DeNovoCNN/denovonet/dataset.py", line 370, in apply_models_on_trio
    dataset.apply_model(
  File "/home/srng3/DeNovoCNN/DeNovoCNN/denovonet/dataset.py", line 135, in apply_model
    results = pool.map(
  File "/home/srng3/anaconda3/envs/tensorflow_env/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/srng3/anaconda3/envs/tensorflow_env/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
OSError: SavedModel file does not exist at: ~/DeNovoCNN/DeNovoCNN/models/snp/{saved_model.pbtxt|saved_model.pb}
DenovoCNN finished.
Output in:
~/research-data/wnt9b_mice_genome_seq/WGS_bam/denovoconn/dnvcnn_dragen-2-9//prediction00.csv

**Comment by gelana** [comment]
What does `ls -lah /DeNovoCNN/DeNovoCNN/models/snp` output?

**Comment by soumyarao86** [comment]
(base) srng3@KC-DS-BioLinux:~/research-data/wnt9b_mice_genome_seq/WGS_bam$ ls -lah ~/DeNovoCNN/DeNovoCNN/models/snp
total 744K
drwxrwx--- 3 srng3 srng3 4.0K Jun 22 17:10 .
drwxrwx--- 5 srng3 srng3 4.0K Jun 22 17:10 ..
-rwxrwx--- 1 srng3 srng3 729K Jun 22 17:10 saved_model.pb
drwxrwx--- 2 srng3 srng3 4.0K Jun 22 17:10 variables

**Comment by gelana** [comment]
Hmm, the model is definitely there. Maybe something goes wrong with relative paths, also worth trying using absolute paths, like: 

`/home/srng3/DeNovoCNN/DeNovoCNN/apply_denovocnn.sh -w=/home/srng3/research-data/wnt9b_mice_genome_seq/WGS_bam/denovoconn/dnvcnn_dragen-2-9/ -v=part_variants00.txt -cb=/home/srng3/research-data/wnt9b_mice_genome_seq/WGS_bam/Cox-2-9.bam -fb=/home/srng3/research-data/wnt9b_mice_genome_seq/WGS_bam/Cox_1529.bam -mb=/home/srng3/research-data/wnt9b_mice_genome_seq/WGS_bam/Cox-4266-TA.bam -sm=/home/srng3/DeNovoCNN/DeNovoCNN/models/snp -im=/home/srng3/DeNovoCNN/DeNovoCNN/models/ins -dm=/home/srng3/DeNovoCNN/DeNovoCNN/models/del -g=/home/srng3/research-data/wnt9b_mice_genome_seq/WGS_bam/GRCm38.primary_assembly.genome.fa -o=prediction00.csv`

Maybe I got some of the paths wrong, just to illustrate the idea :)

**Comment by soumyarao86** [comment]
Thank you!
Seems to be running for now, will see how it goes.
I should be able to see prediction00.csv in the directory I gave, right?
Then I should repeat it with 9 other files, part_variants01.txt-part_variants09.txt and combine the output.

**Comment by soumyarao86** [comment]
Hi Gelana,

The run was successful. Thanks a lot for helping me through it.
However the results were a little disappointing with many false positives (checked in IGV) with a probability of 0.85.
Some even had a probability of 0.92.
I will need to filter it further, removing the variants even if one read is present in the parents.
May be due to the fact that my vcf fle wasn't recalibrated. I will try to run it again after running BQSR.

I have trouble with different probabilities and coverage at the same positions for some calls, while there is no other variant seen in IGV.
chr1    176772419       C       CATCT   0.981   28      38      32      
chr1    176772419       C       <NON_REF>       0.855   26      36      32     

I have attached my input and output files for your reference.
There are quite a lot of such calls.
If you have come across similar issues and found a solution, please let me know. 

[prediction00.csv](https://github.com/ksablauskas/denovocnn/files/8983686/prediction00.csv)
[part_variants00.txt](https://github.com/ksablauskas/denovocnn/files/8983687/part_variants00.txt)

**Comment by gelana** [comment]
Hi @soumyarao86, 

Happy to hear that the run finished successfully. 
By looking quickly through the file I noticed, that it contains a lot of rows with <NON_REF>  field. DeNovoCNN can't handle this value properly, so I suggest filter out all the rows that contain this. The issue that you are observing with different probabilities and coverage is related to that fact .
Also, from our experience we know, that in case of indels more stringent filtering rules should be applied in order to get the reliable calls.

**Comment by soumyarao86** [comment]
Thank you so much for guiding me through it!
I will remove <NON_REF> and run again.
Will try to figure out the stringent parameters for indels.
